config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet

  validates :body, presence: true

  after_create_commit -> { broadcast_append_to tweet}
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :body, presence: true
    validates :likes, :retweets, presence: true, numericality: { :greater_than_or_equal_to => 0 }

    has_many :comments, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_tweet

    def create
        @comment = @tweet.comments.create!(comment_params)

        respond_to do |format|
            if @comment.save!        
                format.turbo_stream
                format.html { redirect_to @tweet }
            else
                format.html { render :new, status: :unprocessable_entity }
            end
        end
    end

    private

    def comment_params
        params.require(:comment).permit(:body)
    end

    def set_tweet
        @tweet = Tweet.find(params[:tweet_id])
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1 or /tweets/1.json
  def show
    @comment = Tweet.find(params['id']).comments.new
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        # format.turbo_stream { render turbo_stream: turbo_stream.replace(@tweets, partial: 'form', locals: {tweet: @tweet}) }
        # format.html { redirect_to tweets_url, notice: "Tweet was successfully created." }
        format.turbo_stream
        # format.html { redirect_to @tweet }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@tweet, partial: 'form', locals: {tweet: @tweet}) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:body, :likes, :retweets)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/comments/_comment.html.erb
<p id='<%= dom_id comment %>'>
    <%= comment.created_at.to_s(:short) %>: <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [@comment.tweet, @comment], url: tweet_comments_path(@tweet), data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"} do |form| %>
  <div>
    <%= form.text_field :body, class: 'input', placeholder: true %>
  </div>
  <div>
    <%= form.submit "Save", class: 'create-tweet-button' %>
  </div>
<% end %>

app/views/comments/_show.html.erb
<div>
  <%= comment.body %>
</div>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append 'comments', @comment%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwirePoc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
    
    <%= yield :head %>
    <%= turbo_include_tags %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with model: tweet, data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"} do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div data-controller='input' class='input-container'>
    <div>
      <%= form.label 'Write your tweet here' %>
      <%= form.text_area :body, class: 'input', data: { action: 'input#onChange' } %>
    </div>

    <div class="actions">
      <%= form.submit class: 'disabled-create-tweet-button', data: { 'input-target': 'source'} %>
    </div>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<p id='<%= dom_id tweet %>'>
  <div data-controller="clipboard" class='tweet'>
    <div class='bodyItem' input data-clipboard-target="source" ><%= tweet.body %></div>
    <div class='tableInfo'>
      Likes: <%= tweet.likes %> &nbsp;&nbsp;|
      Retweets: <%= tweet.retweets %>
    </div>
    <div class='tableActions'>
      <%= link_to 'Show', tweet %>
      <%= link_to 'Edit', edit_tweet_path(tweet) %>
      <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
      <a href="#" data-action="clipboard#copy" >Copy to Clipboard</a>
    </div>
  </div>
</p>

app/views/tweets/create.turbo_stream.erb
<%= turbo_stream.append 'tweets', @tweet%>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= turbo_frame_tag dom_id(@tweet) do%>
  <%= render 'form', tweet: @tweet %>
<% end %>
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div data-controller="colors", data-colors-target="heading">

  <p id="notice"><%= notice %></p>

  <div class="title">
    <div> </div>
    <h1>Best Tweeter PoC of the world</h1>
    <div class="btn btn-primary", data-action="click->colors#change", data-colors-target="button">Switch to dark!</div>
  </div>

  <%= turbo_frame_tag 'new_tweet', src: new_tweet_path(@tweet) do %>
    <%= link_to 'New Tweet', new_tweet_path %>
  <% end %>

  <%= turbo_stream_from @tweet %>

  <div class='tweet-container'>
    <%= turbo_frame_tag "tweets" do %>
      <% render @tweets %>
    <% end %>
  </div>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= turbo_frame_tag 'new_tweet' do%>
  <%= render 'form', tweet: @tweet %>
<% end %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<%= turbo_frame_tag dom_id(@tweet) do%>
  <p>
    <strong>Body:</strong>
    <%= @tweet.body %>
  </p>

  <p>
    <strong>Likes:</strong>
    <%= @tweet.likes %>
  </p>

  <p>
    <strong>Retweets:</strong>
    <%= @tweet.retweets %>
  </p>
  <%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<% end %>


  <%= link_to 'Back', tweets_path %>

<%= turbo_stream_from @tweet %>

<div>
  <br>
  <strong>Comments</strong>
  <%= turbo_frame_tag "comments" do %>
        <% render @tweet.comments %>
  <% end %>

  <div >
    <%= render partial: "comments/form" %>
  </div>
</div>